---
- name: Update repo
  become: true
  ansible.builtin.apt:
    update-cache: true

- name: Install curl, ca-certification
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    update-cache: true
    state: present

- name: Add apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install docker 
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add user group
  become: true
  ansible.builtin.user:
    name: student
    groups:
      - docker
    append: true
