--- 
- name: Nxinx web server
  hosts: all
  tasks:
    - name: Install nxing and Apach
      become: true 
      ansible.builtin.apt:
        update-chache: yes
        name: nginx
        state: present
      when: ansible.os_family == "Debian"

    - name: Install apache
      become: true
      ansible.builtin.yum: 
        name: apache2
        state: present 
      when: ansible.os_family == "RedHat"
